import type { CuratedStory } from "./types"

/** Additional bundled stories (beginner / intermediate). */
export const CURATED_STORIES_EXTRA: CuratedStory[] = [
  {
    id: "morning-walk",
    title: "朝の散歩",
    level: "beginner",
    length: "short",
    tags: ["daily life", "nature"],
    text: "毎朝、おじいちゃんは公園を散歩します。今日も小鳥の声が聞こえます。ベンチに座って、ゆっくりコーヒーを飲みます。近くの子供が「おはよう」と言いました。おじいちゃんは笑顔で手を振りました。",
  },
  {
    id: "lost-umbrella",
    title: "忘れた傘",
    level: "beginner",
    length: "short",
    tags: ["daily life", "school"],
    text: "学校が終わって、ミオは家に帰ろうとしました。でも、雨が降り始めました。ミオは傘を持っていません。友達のアキが「一緒に使おう」と言いました。二人は一つの傘で、ゆっくり歩きました。",
  },
  {
    id: "bakery-smell",
    title: "パン屋の匂い",
    level: "beginner",
    length: "short",
    tags: ["food", "town"],
    text: "駅の近くに小さなパン屋があります。毎日、温かいパンの匂いが道に広がります。今日、トモはクロワッサンを買いました。外はカリッとして、中はふわふわでした。トモはとても満足しました。",
  },
  {
    id: "new-plant",
    title: "新しい植物",
    level: "beginner",
    length: "short",
    tags: ["home", "nature"],
    text: "リエは窓のそばに小さな植物を置きました。毎朝、水をあげます。一週間後、新しい葉が出ました。リエは「よく頑張ったね」と植物に話しかけました。植物は静かに、光を浴びていました。",
  },
  {
    id: "homework-help",
    title: "宿題の手伝い",
    level: "beginner",
    length: "short",
    tags: ["family", "school"],
    text: "弟のカズキは算数の宿題で困っていました。姉のサラは隣に座って、やさしく説明しました。カズキは少しずつ分かってきました。最後に、二人で「できた！」と言いました。お母さんも嬉しそうに微笑みました。",
  },
  {
    id: "bus-stop",
    title: "バス停で",
    level: "beginner",
    length: "short",
    tags: ["travel", "daily life"],
    text: "バス停で、老人が地図を見ていました。ユウタは近づいて、行き先を聞きました。バスが来たので、二人で乗りました。老人は「若い人は親切ね」と言いました。ユウタは少し照れましたが、よかったと思いました。",
  },
  {
    id: "snow-day",
    title: "雪の日",
    level: "beginner",
    length: "short",
    tags: ["weather", "winter"],
    text: "朝起きると、外は真っ白でした。雪が静かに降っています。ハルカは手袋をはめて、庭に出ました。小さな雪だるまを作りました。お父さんが写真を撮ってくれました。ハルカはとても楽しかったです。",
  },
  {
    id: "library-card",
    title: "図書館カード",
    level: "beginner",
    length: "medium",
    tags: ["school", "books"],
    text: "今日、イツキは初めて図書館カードを作りました。先生が使い方を教えてくれました。イツキは恐竜の本を借りました。家に帰って、すぐに読み始めました。ページをめくる音が、部屋に静かに響きました。一時間後、イツキは「明日も来たい」と言いました。",
  },
  {
    id: "lunch-box",
    title: "お弁当",
    level: "beginner",
    length: "medium",
    tags: ["food", "school"],
    text: "マイは初めて自分でお弁当を作りました。ご飯、卵焼き、トマトを入れました。学校で開けると、友達が「おいしそう」と言いました。マイは少し恥ずかしかったけれど、とても嬉しかったです。昼休み、みんなで一緒に食べました。",
  },
  {
    id: "pet-hamster",
    title: "ハムスター",
    level: "beginner",
    length: "medium",
    tags: ["animals", "home"],
    text: "ノアは小さなハムスターをもらいました。名前はモチです。モチは毎晩、回し車を走ります。ノアはエサと水を忘れないようにしています。ある日、モチがノアの手の上で眠りました。ノアは「信頼してくれたんだ」と感じました。",
  },
  {
    id: "cleaning-day",
    title: "掃除の日",
    level: "beginner",
    length: "medium",
    tags: ["home", "family"],
    text: "日曜日は家族で掃除をします。お父さんはリビング、お母さんは台所、レナは自分の部屋を片付けます。レナは古いおもちゃを箱に入れました。掃除が終わると、部屋は明るくなりました。みんなでジュースを飲んで、休憩しました。",
  },
  {
    id: "cloud-watching",
    title: "雲を見る",
    level: "beginner",
    length: "medium",
    tags: ["nature", "friends"],
    text: "午後、二人の友達は丘の上で雲を見ました。一つは犬の形、もう一つは船の形に見えました。風が少し吹いて、草が揺れました。シオリは「空は毎日違うね」と言いました。ヒナタは「でも、今日は特にきれいだ」と答えました。",
  },
  {
    id: "dentist-visit",
    title: "歯医者",
    level: "intermediate",
    length: "medium",
    tags: ["health", "daily life"],
    text: "ケイゴは歯医者の予約の日でした。最初は少し緊張しましたが、先生はやさしく話しかけてくれました。治療は思ったより早く終わりました。先生は「よく磨いているね」と言いました。ケイゴは安心して、コンビニでアイスを買いました。",
  },
  {
    id: "part-time-job",
    title: "初バイト",
    level: "intermediate",
    length: "medium",
    tags: ["work", "school"],
    text: "高校生のミサキは、近くのカフェで初めてバイトを始めました。最初はメニューを覚えるのが大変でした。先輩が丁寧に教えてくれたので、少しずつ自信がつきました。閉店後、店長が「今日もありがとう」と言いました。ミサキは疲れましたが、充実感がありました。",
  },
  {
    id: "email-mistake",
    title: "メールの間違い",
    level: "intermediate",
    length: "medium",
    tags: ["school", "humor"],
    text: "タケシは先生にメールを送りました。後で、間違ったファイルを添付していたことに気づきました。顔が赤くなり、すぐに訂正のメールを送りました。先生は「大丈夫、よくあるよ」と返信してくれました。タケシは次から確認することを決めました。",
  },
  {
    id: "cooking-class",
    title: "料理教室",
    level: "intermediate",
    length: "medium",
    tags: ["food", "friends"],
    text: "週末、ユイと友達は料理教室に行きました。今日のメニューはカレーです。野菜を切るのは難しかったですが、みんなで協力しました。完成したカレーはとても香りがよかったです。講師は「家庭でも作ってみてね」と言いました。",
  },
  {
    id: "missed-bus",
    title: "バスを逃した日",
    level: "intermediate",
    length: "medium",
    tags: ["travel", "problem"],
    text: "アオイは朝、バス停に着いたとき、バスが今出発するところでした。次のバスは二十分後です。アオイは急いで自転車を取りに戻り、学校へ向かいました。教室に入ると、先生が「安全が一番」と言いました。アオイは次から早めに家を出ることにしました。",
  },
  {
    id: "language-exchange",
    title: "言語交換",
    level: "intermediate",
    length: "long",
    tags: ["language", "friendship"],
    text: "大学のダニは、言語交換のイベントに参加しました。最初は緊張しましたが、相手の学生はフレンドリーでした。二人は半分日本語、半分英語で話しました。間違えても、お互いに笑い合いました。別れ際、連絡先を交換して、来週また会う約束をしました。",
  },
  {
    id: "weekend-market",
    title: "週末の朝市",
    level: "intermediate",
    length: "long",
    tags: ["shopping", "town"],
    text: "土曜日の朝、リョウと祖母は朝市に行きました。新鮮な野菜、魚、手作りのジャムが並んでいました。祖母は昔ながらの店の人と挨拶を交わしました。リョウは初めて見る食材が多く、質問をたくさんしました。帰り道、二人は重い袋を持ちながらも、楽しい時間だったと言いました。",
  },
  {
    id: "school-festival",
    title: "文化祭",
    level: "intermediate",
    length: "long",
    tags: ["school", "festival"],
    text: "文化祭の前日、クラスみんなで教室を飾りました。壁にポスターを貼り、机を並べ替えました。夜まで残った数人は、疲れながらも笑い合いました。当日、たくさんの来場者が教室を訪れました。午後、売上を数えて、クラス全員で写真を撮りました。先生は「最高のチームワークだった」と言いました。",
  },
]
