/** Compact EN glosses for curated stories + common particles. */
export interface GlossEntry {
  reading?: string
  definition: string
}

export const GLOSSARY: Record<string, GlossEntry> = {
  // Particles & grammar
  "は": { reading: "は", definition: "(topic marker)" },
  "が": { reading: "が", definition: "(subject marker)" },
  "を": { reading: "を", definition: "(object marker)" },
  "に": { reading: "に", definition: "(to / at / in)" },
  "で": { reading: "で", definition: "(at / by / with)" },
  "も": { reading: "も", definition: "(also / too)" },
  "の": { reading: "の", definition: "(possessive / of)" },
  "と": { reading: "と", definition: "(and / with)" },
  "から": { reading: "から", definition: "(from / because)" },
  "まで": { reading: "まで", definition: "(until / as far as)" },
  "へ": { reading: "へ", definition: "(toward)" },
  "か": { reading: "か", definition: "(question)" },
  "よ": { reading: "よ", definition: "(emphasis)" },
  "ね": { reading: "ね", definition: "(isn't it?)" },
  "より": { reading: "より", definition: "(than / from)" },
  "など": { reading: "など", definition: "(such as / etc.)" },
  "けれど": { reading: "けれど", definition: "(but / however)" },
  "けれども": { reading: "けれども", definition: "(but / however)" },
  "ので": { reading: "ので", definition: "(because / since)" },
  "のに": { reading: "のに", definition: "(although / despite)" },
  "て": { reading: "て", definition: "(te-form connector)" },
  "た": { reading: "た", definition: "(past tense)" },
  "だ": { reading: "だ", definition: "(copula)" },
  "です": { reading: "です", definition: "(polite copula)" },
  "ます": { reading: "ます", definition: "(polite verb ending)" },
  "ました": { reading: "ました", definition: "(polite past)" },
  "ません": { reading: "ません", definition: "(polite negative)" },
  "ましょう": { reading: "ましょう", definition: "(let's / shall we)" },
  "いる": { reading: "いる", definition: "to exist; to be (animate)" },
  "ある": { reading: "ある", definition: "to exist; to be (inanimate)" },
  "する": { reading: "する", definition: "to do" },
  "なる": { reading: "なる", definition: "to become" },
  "いく": { reading: "いく", definition: "to go" },
  "くる": { reading: "くる", definition: "to come" },
  "みる": { reading: "みる", definition: "to see; to look" },
  "いう": { reading: "いう", definition: "to say" },
  "おもう": { reading: "おもう", definition: "to think" },
  "しる": { reading: "しる", definition: "to know" },
  "できる": { reading: "できる", definition: "can do; to be able" },
  "ほしい": { reading: "ほしい", definition: "to want (thing)" },
  "この": { reading: "この", definition: "this" },
  "その": { reading: "その", definition: "that" },
  "あの": { reading: "あの", definition: "that (over there)" },
  "どの": { reading: "どの", definition: "which" },
  "ここ": { reading: "ここ", definition: "here" },
  "そこ": { reading: "そこ", definition: "there" },
  "あそこ": { reading: "あそこ", definition: "over there" },
  "とても": { reading: "とても", definition: "very" },
  "ちょっと": { reading: "ちょっと", definition: "a little" },
  "たくさん": { reading: "たくさん", definition: "many; a lot" },
  "少し": { reading: "すこし", definition: "a little; slightly" },
  "少ない": { reading: "すくない", definition: "few; little" },
  "大きい": { reading: "おおきい", definition: "big; large" },
  "大きな": { reading: "おおきな", definition: "big; large" },
  "小さい": { reading: "ちいさい", definition: "small" },
  "小さな": { reading: "ちいさな", definition: "small; little" },
  "新しい": { reading: "あたらしい", definition: "new" },
  "古い": { reading: "ふるい", definition: "old" },
  "高い": { reading: "たかい", definition: "high; tall; expensive" },
  "低い": { reading: "ひくい", definition: "low" },
  "長い": { reading: "ながい", definition: "long" },
  "短い": { reading: "みじかい", definition: "short" },
  "早い": { reading: "はやい", definition: "early; fast" },
  "遅い": { reading: "おそい", definition: "late; slow" },
  "暑い": { reading: "あつい", definition: "hot (weather)" },
  "寒い": { reading: "さむい", definition: "cold (weather)" },
  "暖かい": { reading: "あたたかい", definition: "warm" },
  "涼しい": { reading: "すずしい", definition: "cool; refreshing" },
  "明るい": { reading: "あかるい", definition: "bright; cheerful" },
  "暗い": { reading: "くらい", definition: "dark" },
  "楽しい": { reading: "たのしい", definition: "fun; enjoyable" },
  "悲しい": { reading: "かなしい", definition: "sad" },
  "嬉しい": { reading: "うれしい", definition: "happy; glad" },
  "怖い": { reading: "こわい", definition: "scary; afraid" },
  "忙しい": { reading: "いそがしい", definition: "busy" },
  "静か": { reading: "しずか", definition: "quiet" },
  "元気": { reading: "げんき", definition: "healthy; energetic" },
  "きれい": { reading: "きれい", definition: "pretty; clean" },
  "おいしい": { reading: "おいしい", definition: "delicious" },
  "まずい": { reading: "まずい", definition: "bad-tasting" },
  "便利": { reading: "べんり", definition: "convenient" },
  "有名": { reading: "ゆうめい", definition: "famous" },
  "大切": { reading: "たいせつ", definition: "important; precious" },
  "大丈夫": { reading: "だいじょうぶ", definition: "okay; all right" },
  "同じ": { reading: "おなじ", definition: "same" },
  "違う": { reading: "ちがう", definition: "different; wrong" },
  "多い": { reading: "おおい", definition: "many" },
  "人": { reading: "ひと", definition: "person; people" },
  "男": { reading: "おとこ", definition: "man; boy" },
  "女": { reading: "おんな", definition: "woman; girl" },
  "子供": { reading: "こども", definition: "child" },
  "友達": { reading: "ともだち", definition: "friend" },
  "家族": { reading: "かぞく", definition: "family" },
  "お母さん": { reading: "おかあさん", definition: "mother" },
  "お父さん": { reading: "おとうさん", definition: "father" },
  "兄": { reading: "あに", definition: "older brother" },
  "姉": { reading: "あね", definition: "older sister" },
  "弟": { reading: "おとうと", definition: "younger brother" },
  "妹": { reading: "いもうと", definition: "younger sister" },
  "先生": { reading: "せんせい", definition: "teacher" },
  "学生": { reading: "がくせい", definition: "student" },
  "学校": { reading: "がっこう", definition: "school" },
  "教室": { reading: "きょうしつ", definition: "classroom" },
  "家": { reading: "いえ", definition: "house; home" },
  "部屋": { reading: "へや", definition: "room" },
  "町": { reading: "まち", definition: "town" },
  "村": { reading: "むら", definition: "village" },
  "店": { reading: "みせ", definition: "shop; store" },
  "駅": { reading: "えき", definition: "station" },
  "道": { reading: "みち", definition: "road; way" },
  "橋": { reading: "はし", definition: "bridge" },
  "公園": { reading: "こうえん", definition: "park" },
  "森": { reading: "もり", definition: "forest" },
  "山": { reading: "やま", definition: "mountain" },
  "川": { reading: "かわ", definition: "river" },
  "海": { reading: "うみ", definition: "sea; ocean" },
  "空": { reading: "そら", definition: "sky" },
  "太陽": { reading: "たいよう", definition: "sun" },
  "月": { reading: "つき", definition: "month; moon" },
  "週": { reading: "しゅう", definition: "week" },
  "日": { reading: "ひ", definition: "day; sun" },
  "曜日": { reading: "ようび", definition: "day of the week" },
  "月曜日": { reading: "げつようび", definition: "Monday" },
  "火曜日": { reading: "かようび", definition: "Tuesday" },
  "水曜日": { reading: "すいようび", definition: "Wednesday" },
  "木曜日": { reading: "もくようび", definition: "Thursday" },
  "金曜日": { reading: "きんようび", definition: "Friday" },
  "土曜日": { reading: "どようび", definition: "Saturday" },
  "日曜日": { reading: "にちようび", definition: "Sunday" },
  "春": { reading: "はる", definition: "spring" },
  "夏": { reading: "なつ", definition: "summer" },
  "秋": { reading: "あき", definition: "autumn" },
  "冬": { reading: "ふゆ", definition: "winter" },
  "犬": { reading: "いぬ", definition: "dog" },
  "猫": { reading: "ねこ", definition: "cat" },
  "鳥": { reading: "とり", definition: "bird" },
  "魚": { reading: "さかな", definition: "fish" },
  "馬": { reading: "うま", definition: "horse" },
  "牛": { reading: "うし", definition: "cow" },
  "象": { reading: "ぞう", definition: "elephant" },
  "ライオン": { reading: "ライオン", definition: "lion" },
  "キツネ": { reading: "キツネ", definition: "fox" },
  "うさぎ": { reading: "うさぎ", definition: "rabbit" },
  "虫": { reading: "むし", definition: "insect; bug" },
  "花": { reading: "はな", definition: "flower" },
  "木": { reading: "き", definition: "tree; wood" },
  "草": { reading: "くさ", definition: "grass" },
  "葉": { reading: "は", definition: "leaf" },
  "果物": { reading: "くだもの", definition: "fruit" },
  "野菜": { reading: "やさい", definition: "vegetable" },
  "りんご": { reading: "りんご", definition: "apple" },
  "みかん": { reading: "みかん", definition: "mandarin orange" },
  "バナナ": { reading: "バナナ", definition: "banana" },
  "パン": { reading: "パン", definition: "bread" },
  "ご飯": { reading: "ごはん", definition: "rice; meal" },
  "水": { reading: "みず", definition: "water" },
  "お茶": { reading: "おちゃ", definition: "tea" },
  "コーヒー": { reading: "コーヒー", definition: "coffee" },
  "牛乳": { reading: "ぎゅうにゅう", definition: "milk" },
  "肉": { reading: "にく", definition: "meat" },
  "卵": { reading: "たまご", definition: "egg" },
  "食べ物": { reading: "たべもの", definition: "food" },
  "飲み物": { reading: "のみもの", definition: "drink; beverage" },
  "朝ごはん": { reading: "あさごはん", definition: "breakfast" },
  "昼ごはん": { reading: "ひるごはん", definition: "lunch" },
  "晩ごはん": { reading: "ばんごはん", definition: "dinner" },
  "料理": { reading: "りょうり", definition: "cooking; dish" },
  "作る": { reading: "つくる", definition: "to make" },
  "食べる": { reading: "たべる", definition: "to eat" },
  "飲む": { reading: "のむ", definition: "to drink" },
  "買う": { reading: "かう", definition: "to buy" },
  "売る": { reading: "うる", definition: "to sell" },
  "持つ": { reading: "もつ", definition: "to hold; to have" },
  "置く": { reading: "おく", definition: "to put; to place" },
  "取る": { reading: "とる", definition: "to take" },
  "渡す": { reading: "わたす", definition: "to hand over" },
  "開ける": { reading: "あける", definition: "to open" },
  "閉める": { reading: "しめる", definition: "to close" },
  "入る": { reading: "はいる", definition: "to enter" },
  "出る": { reading: "でる", definition: "to exit; to leave" },
  "走る": { reading: "はしる", definition: "to run" },
  "歩く": { reading: "あるく", definition: "to walk" },
  "泳ぐ": { reading: "およぐ", definition: "to swim" },
  "飛ぶ": { reading: "とぶ", definition: "to fly" },
  "座る": { reading: "すわる", definition: "to sit" },
  "立つ": { reading: "たつ", definition: "to stand" },
  "寝る": { reading: "ねる", definition: "to sleep" },
  "起きる": { reading: "おきる", definition: "to wake up" },
  "働く": { reading: "はたらく", definition: "to work" },
  "勉強": { reading: "べんきょう", definition: "study" },
  "勉強する": { reading: "べんきょうする", definition: "to study" },
  "読む": { reading: "よむ", definition: "to read" },
  "書く": { reading: "かく", definition: "to write" },
  "聞く": { reading: "きく", definition: "to listen; to ask" },
  "話す": { reading: "はなす", definition: "to speak" },
  "教える": { reading: "おしえる", definition: "to teach" },
  "習う": { reading: "ならう", definition: "to learn" },
  "覚える": { reading: "おぼえる", definition: "to remember; to memorize" },
  "忘れる": { reading: "わすれる", definition: "to forget" },
  "考える": { reading: "かんがえる", definition: "to think; to consider" },
  "探す": { reading: "さがす", definition: "to search for; to look for" },
  "見つける": { reading: "みつける", definition: "to find" },
  "待つ": { reading: "まつ", definition: "to wait" },
  "会う": { reading: "あう", definition: "to meet" },
  "遊ぶ": { reading: "あそぶ", definition: "to play" },
  "笑う": { reading: "わらう", definition: "to laugh" },
  "泣く": { reading: "なく", definition: "to cry" },
  "歌う": { reading: "うたう", definition: "to sing" },
  "踊る": { reading: "おどる", definition: "to dance" },
  "描く": { reading: "えがく", definition: "to draw" },
  "洗う": { reading: "あらう", definition: "to wash" },
  "着る": { reading: "きる", definition: "to wear" },
  "脱ぐ": { reading: "ぬぐ", definition: "to take off (clothes)" },
  "使う": { reading: "つかう", definition: "to use" },
  "住む": { reading: "すむ", definition: "to live (somewhere)" },
  "住んでいる": { reading: "すんでいる", definition: "to be living" },
  "住んでいました": { reading: "すんでいました", definition: "was living; lived" },
  "始める": { reading: "はじめる", definition: "to begin" },
  "終わる": { reading: "おわる", definition: "to end" },
  "続ける": { reading: "つづける", definition: "to continue" },
  "止まる": { reading: "とまる", definition: "to stop" },
  "降る": { reading: "ふる", definition: "to fall (rain/snow)" },
  "晴れる": { reading: "はれる", definition: "to clear up (weather)" },
  "曇る": { reading: "くもる", definition: "to become cloudy" },
  "吹く": { reading: "ふく", definition: "to blow (wind)" },
  "色": { reading: "いろ", definition: "color" },
  "赤": { reading: "あか", definition: "red" },
  "青": { reading: "あお", definition: "blue" },
  "青い": { reading: "あおい", definition: "blue" },
  "白": { reading: "しろ", definition: "white" },
  "黒": { reading: "くろ", definition: "black" },
  "黄色": { reading: "きいろ", definition: "yellow" },
  "緑": { reading: "みどり", definition: "green" },
  "服": { reading: "ふく", definition: "clothes" },
  "靴": { reading: "くつ", definition: "shoes" },
  "帽子": { reading: "ぼうし", definition: "hat" },
  "傘": { reading: "かさ", definition: "umbrella" },
  "鞄": { reading: "かばん", definition: "bag" },
  "本": { reading: "ほん", definition: "book" },
  "紙": { reading: "かみ", definition: "paper" },
  "鉛筆": { reading: "えんぴつ", definition: "pencil" },
  "机": { reading: "つくえ", definition: "desk" },
  "椅子": { reading: "いす", definition: "chair" },
  "窓": { reading: "まど", definition: "window" },
  "ドア": { reading: "ドア", definition: "door" },
  "電話": { reading: "でんわ", definition: "telephone" },
  "車": { reading: "くるま", definition: "car" },
  "電車": { reading: "でんしゃ", definition: "train" },
  "バス": { reading: "バス", definition: "bus" },
  "自転車": { reading: "じてんしゃ", definition: "bicycle" },
  "飛行機": { reading: "ひこうき", definition: "airplane" },
  "船": { reading: "ふね", definition: "ship; boat" },
  "切符": { reading: "きっぷ", definition: "ticket" },
  "お金": { reading: "おかね", definition: "money" },
  "仕事": { reading: "しごと", definition: "job; work" },
  "病院": { reading: "びょういん", definition: "hospital" },
  "薬": { reading: "くすり", definition: "medicine" },
  "体": { reading: "からだ", definition: "body" },
  "頭": { reading: "あたま", definition: "head" },
  "目": { reading: "め", definition: "eye" },
  "耳": { reading: "みみ", definition: "ear" },
  "口": { reading: "くち", definition: "mouth" },
  "手": { reading: "て", definition: "hand" },
  "足": { reading: "あし", definition: "foot; leg" },
  "心": { reading: "こころ", definition: "heart; mind" },
  "声": { reading: "こえ", definition: "voice" },
  "顔": { reading: "かお", definition: "face" },
  "上": { reading: "うえ", definition: "above; on top" },
  "下": { reading: "した", definition: "below; under" },
  "中": { reading: "なか", definition: "inside; middle" },
  "外": { reading: "そと", definition: "outside" },
  "右": { reading: "みぎ", definition: "right" },
  "左": { reading: "ひだり", definition: "left" },
  "近く": { reading: "ちかく", definition: "nearby" },
  "遠く": { reading: "とおく", definition: "far away" },
  "隣": { reading: "となり", definition: "next to; neighbor" },
  "向こう": { reading: "むこう", definition: "over there; opposite side" },
  "こちら": { reading: "こちら", definition: "this way; here (polite)" },
  "あちら": { reading: "あちら", definition: "that way (polite)" },
  "一": { reading: "いち", definition: "one" },
  "二": { reading: "に", definition: "two" },
  "三": { reading: "さん", definition: "three" },
  "四": { reading: "よん", definition: "four" },
  "五": { reading: "ご", definition: "five" },
  "六": { reading: "ろく", definition: "six" },
  "七": { reading: "なな", definition: "seven" },
  "八": { reading: "はち", definition: "eight" },
  "九": { reading: "きゅう", definition: "nine" },
  "十": { reading: "じゅう", definition: "ten" },
  "百": { reading: "ひゃく", definition: "hundred" },
  "千": { reading: "せん", definition: "thousand" },
  "万": { reading: "まん", definition: "ten thousand" },
  "一つ": { reading: "ひとつ", definition: "one (thing)" },
  "二つ": { reading: "ふたつ", definition: "two (things)" },
  "三つ": { reading: "みっつ", definition: "three (things)" },
  "一人": { reading: "ひとり", definition: "one person" },
  "二人": { reading: "ふたり", definition: "two people" },
  "三人": { reading: "さんにん", definition: "three people" },
  "四人": { reading: "よにん", definition: "four people" },
  "五人": { reading: "ごにん", definition: "five people" },
  "六人": { reading: "ろくにん", definition: "six people" },
  "七人": { reading: "ななにん", definition: "seven people" },
  "八人": { reading: "はちにん", definition: "eight people" },
  "九人": { reading: "きゅうにん", definition: "nine people" },
  "十人": { reading: "じゅうにん", definition: "ten people" },
  "昔々": { reading: "むかしむかし", definition: "once upon a time" },
  "ある日": { reading: "あるひ", definition: "one day" },
  "毎朝": { reading: "まいあさ", definition: "every morning" },
  "毎晩": { reading: "まいばん", definition: "every evening" },
  "初めて": { reading: "はじめて", definition: "for the first time" },
  "急に": { reading: "きゅうに", definition: "suddenly" },
  "ゆっくり": { reading: "ゆっくり", definition: "slowly; leisurely" },
  "すぐ": { reading: "すぐ", definition: "immediately; soon" },
  "もう": { reading: "もう", definition: "already" },
  "まだ": { reading: "まだ", definition: "still; not yet" },
  "いつも": { reading: "いつも", definition: "always" },
  "時々": { reading: "ときどき", definition: "sometimes" },
  "よく": { reading: "よく", definition: "often; well" },
  "あまり": { reading: "あまり", definition: "not very (with negative)" },
  "全然": { reading: "ぜんぜん", definition: "not at all (with negative)" },
  "本当": { reading: "ほんとう", definition: "really; truth" },
  "本当に": { reading: "ほんとうに", definition: "really; truly" },
  "確か": { reading: "たしか", definition: "certainly; if I recall" },
  "多分": { reading: "たぶん", definition: "probably" },
  "きっと": { reading: "きっと", definition: "surely; definitely" },
  "一緒": { reading: "いっしょ", definition: "together" },
  "一人で": { reading: "ひとりで", definition: "alone; by oneself" },
  "自分": { reading: "じぶん", definition: "oneself" },
  "皆": { reading: "みんな", definition: "everyone" },
  "誰": { reading: "だれ", definition: "who" },
  "何": { reading: "なに", definition: "what" },
  "どこ": { reading: "どこ", definition: "where" },
  "いつ": { reading: "いつ", definition: "when" },
  "どう": { reading: "どう", definition: "how" },
  "なぜ": { reading: "なぜ", definition: "why" },
  "物語": { reading: "ものがたり", definition: "story; tale" },
  "夢": { reading: "ゆめ", definition: "dream" },
  "約束": { reading: "やくそく", definition: "promise" },
  "秘密": { reading: "ひみつ", definition: "secret" },
  "問題": { reading: "もんだい", definition: "problem; question" },
  "答え": { reading: "こたえ", definition: "answer" },
  "質問": { reading: "しつもん", definition: "question" },
  "方法": { reading: "ほうほう", definition: "method; way" },
  "理由": { reading: "りゆう", definition: "reason" },
  "意味": { reading: "いみ", definition: "meaning" },
  "気持ち": { reading: "きもち", definition: "feeling; mood" },
  "幸せ": { reading: "しあわせ", definition: "happiness" },
  "幸せな": { reading: "しあわせな", definition: "happy" },
  "不思議": { reading: "ふしぎ", definition: "wonder; mystery" },
  "不思議な": { reading: "ふしぎな", definition: "mysterious; strange" },
  "迷子": { reading: "まいご", definition: "lost child; stray" },
  "子犬": { reading: "こいぬ", definition: "puppy" },
  "市場": { reading: "いちば", definition: "market" },
  "祭り": { reading: "まつり", definition: "festival" },
  "夏祭り": { reading: "なつまつり", definition: "summer festival" },
  "花火": { reading: "はなび", definition: "fireworks" },
  "提灯": { reading: "ちょうちん", definition: "paper lantern" },
  "浴衣": { reading: "ゆかた", definition: "yukata; summer kimono" },
  "転校生": { reading: "てんこうせい", definition: "transfer student" },
  "クラス": { reading: "クラス", definition: "class (school)" },
  "紹介": { reading: "しょうかい", definition: "introduction" },
  "自己紹介": { reading: "じこしょうかい", definition: "self-introduction" },
  "名前": { reading: "なまえ", definition: "name" },
  "国": { reading: "くに", definition: "country" },
  "日本": { reading: "にほん", definition: "Japan" },
  "外国": { reading: "がいこく", definition: "foreign country" },
  "言葉": { reading: "ことば", definition: "word; language" },
  "日本語": { reading: "にほんご", definition: "Japanese language" },
  "英語": { reading: "えいご", definition: "English language" },
  "荷物": { reading: "にもつ", definition: "luggage; baggage" },
  "スーツケース": { reading: "スーツケース", definition: "suitcase" },
  "ホテル": { reading: "ホテル", definition: "hotel" },
  "地図": { reading: "ちず", definition: "map" },
  "道に迷う": { reading: "みちにまよう", definition: "to get lost" },
  "助ける": { reading: "たすける", definition: "to help; to save" },
  "助けて": { reading: "たすけて", definition: "help! (request)" },
  "ありがとう": { reading: "ありがとう", definition: "thank you" },
  "すみません": { reading: "すみません", definition: "excuse me; sorry" },
  "こんにちは": { reading: "こんにちは", definition: "hello; good afternoon" },
  "おはよう": { reading: "おはよう", definition: "good morning" },
  "こんばんは": { reading: "こんばんは", definition: "good evening" },
  "さようなら": { reading: "さようなら", definition: "goodbye" },
  "おやすみ": { reading: "おやすみ", definition: "good night" },
  "いただきます": { reading: "いただきます", definition: "bon appetit (before eating)" },
  "ごちそうさま": { reading: "ごちそうさま", definition: "thanks for the meal" },
  "行く": { reading: "いく", definition: "to go" },
  "来る": { reading: "くる", definition: "to come" },
  "帰る": { reading: "かえる", definition: "to return home" },
  "送る": { reading: "おくる", definition: "to send" },
  "届ける": { reading: "とどける", definition: "to deliver" },
  "届く": { reading: "とどく", definition: "to arrive; to be delivered" },
  "届きました": { reading: "とどきました", definition: "arrived; was delivered" },
  "届けました": { reading: "とどけました", definition: "delivered" },
  "届けます": { reading: "とどけます", definition: "will deliver" },
  "プレゼント": { reading: "プレゼント", definition: "present; gift" },
  "贈り物": { reading: "おくりもの", definition: "gift" },
  "箱": { reading: "はこ", definition: "box" },
  "包む": { reading: "つつむ", definition: "to wrap" },
  "開く": { reading: "ひらく", definition: "to open" },
  "中身": { reading: "なかみ", definition: "contents; inside" },
  "驚く": { reading: "おどろく", definition: "to be surprised" },
  "喜ぶ": { reading: "よろこぶ", definition: "to be delighted" },
  "心配": { reading: "しんぱい", definition: "worry; concern" },
  "心配する": { reading: "しんぱいする", definition: "to worry" },
  "安心": { reading: "あんしん", definition: "relief; peace of mind" },
  "安心する": { reading: "あんしんする", definition: "to feel relieved" },
  "困る": { reading: "こまる", definition: "to be troubled" },
  "決める": { reading: "きめる", definition: "to decide" },
  "選ぶ": { reading: "えらぶ", definition: "to choose" },
  "比べる": { reading: "くらべる", definition: "to compare" },
  "試す": { reading: "ためす", definition: "to try" },
  "成功": { reading: "せいこう", definition: "success" },
  "失敗": { reading: "しっぱい", definition: "failure" },
  "練習": { reading: "れんしゅう", definition: "practice" },
  "練習する": { reading: "れんしゅうする", definition: "to practice" },
  "上手": { reading: "じょうず", definition: "skillful; good at" },
  "下手": { reading: "へた", definition: "unskillful; bad at" },
  "得意": { reading: "とくい", definition: "strong point; good at" },
  "苦手": { reading: "にがて", definition: "weak point; not good at" },
  "好き": { reading: "すき", definition: "to like" },
  "嫌い": { reading: "きらい", definition: "to dislike" },
  "大好き": { reading: "だいすき", definition: "love; really like" },
  "大嫌い": { reading: "だいきらい", definition: "hate; really dislike" },
  "必要": { reading: "ひつよう", definition: "necessary" },
  "大切にする": { reading: "たいせつにする", definition: "to treasure; to cherish" },
  "大切にして": { reading: "たいせつにして", definition: "treasuring; cherishing" },
  "歩き回る": { reading: "あるきまわる", definition: "to walk around" },
  "歩き回りました": { reading: "あるきまわりました", definition: "walked around" },
  "見つけました": { reading: "みつけました", definition: "found" },
  "見つかりました": { reading: "みつかりました", definition: "was found" },
  "探しました": { reading: "さがしました", definition: "searched for" },
  "作りました": { reading: "つくりました", definition: "made" },
  "作って": { reading: "つくって", definition: "making (te-form)" },
  "食べました": { reading: "たべました", definition: "ate" },
  "飲みました": { reading: "のみました", definition: "drank" },
  "行きました": { reading: "いきました", definition: "went" },
  "来ました": { reading: "きました", definition: "came" },
  "帰りました": { reading: "かえりました", definition: "returned home" },
  "言いました": { reading: "いいました", definition: "said" },
  "思いました": { reading: "おもいました", definition: "thought" },
  "分かりました": { reading: "わかりました", definition: "understood" },
  "知りました": { reading: "しりました", definition: "learned; found out" },
  "聞きました": { reading: "ききました", definition: "asked; listened" },
  "読みました": { reading: "よみました", definition: "read" },
  "書きました": { reading: "かきました", definition: "wrote" },
  "買いました": { reading: "かいました", definition: "bought" },
  "待ちました": { reading: "まちました", definition: "waited" },
  "会いました": { reading: "あいました", definition: "met" },
  "遊びました": { reading: "あそびました", definition: "played" },
  "笑いました": { reading: "わらいました", definition: "laughed" },
  "泣きました": { reading: "なきました", definition: "cried" },
  "始めました": { reading: "はじめました", definition: "started" },
  "終わりました": { reading: "おわりました", definition: "ended; finished" },
  "降りました": { reading: "おりました", definition: "got off (train)" },
  "乗りました": { reading: "のりました", definition: "got on (train)" },
  "乗る": { reading: "のる", definition: "to ride; to get on" },
  "降りる": { reading: "おりる", definition: "to get off" },
  "座りました": { reading: "すわりました", definition: "sat down" },
  "立ちました": { reading: "たちました", definition: "stood up" },
  "走りました": { reading: "はしりました", definition: "ran" },
  "歩きました": { reading: "あるきました", definition: "walked" },
  "泳ぎました": { reading: "およぎました", definition: "swam" },
  "歌いました": { reading: "うたいました", definition: "sang" },
  "描きました": { reading: "えがきました", definition: "drew" },
  "洗いました": { reading: "あらいました", definition: "washed" },
  "開けました": { reading: "あけました", definition: "opened" },
  "閉めました": { reading: "しめました", definition: "closed" },
  "入りました": { reading: "はいりました", definition: "entered" },
  "出ました": { reading: "でました", definition: "went out; left" },
  "起きました": { reading: "おきました", definition: "woke up" },
  "寝ました": { reading: "ねました", definition: "slept" },
  "働きました": { reading: "はたらきました", definition: "worked" },
  "勉強しました": { reading: "べんきょうしました", definition: "studied" },
  "教えました": { reading: "おしえました", definition: "taught" },
  "習いました": { reading: "ならいました", definition: "learned" },
  "覚えました": { reading: "おぼえました", definition: "memorized" },
  "忘れました": { reading: "わすれました", definition: "forgot" },
  "考えました": { reading: "かんがえました", definition: "thought about" },
  "決めました": { reading: "きめました", definition: "decided" },
  "選びました": { reading: "えらびました", definition: "chose" },
  "試しました": { reading: "ためしました", definition: "tried" },
  "成功しました": { reading: "せいこうしました", definition: "succeeded" },
  "失敗しました": { reading: "しっぱいしました", definition: "failed" },
  "練習しました": { reading: "れんしゅうしました", definition: "practiced" },
  "助けました": { reading: "たすけました", definition: "helped" },
  "困りました": { reading: "こまりました", definition: "was troubled" },
  "驚きました": { reading: "おどろきました", definition: "was surprised" },
  "喜びました": { reading: "よろこびました", definition: "was delighted" },
  "心配しました": { reading: "しんぱいしました", definition: "worried" },
  "安心しました": { reading: "あんしんしました", definition: "felt relieved" },
  "なりました": { reading: "なりました", definition: "became" },
  "いました": { reading: "いました", definition: "was; existed" },
  "でした": { reading: "でした", definition: "was (polite past)" },
  "でした。": { reading: "でした。", definition: "was (polite past)" },
  // Story-specific verbs & adjectives (dictionary forms)
  "通る": { reading: "とおる", definition: "to pass; to go through" },
  "知らせる": { reading: "しらせる", definition: "to notify; to tell" },
  "止む": { reading: "やむ", definition: "to stop (rain etc.)" },
  "混ぜる": { reading: "まぜる", definition: "to mix" },
  "切る": { reading: "きる", definition: "to cut" },
  "広がる": { reading: "ひろがる", definition: "to spread; to extend" },
  "休む": { reading: "やすむ", definition: "to rest" },
  "振る": { reading: "ふる", definition: "to wave; to shake" },
  "近づく": { reading: "ちかづく", definition: "to approach; to get close" },
  "怖がる": { reading: "こわがる", definition: "to be afraid of" },
  "動く": { reading: "うごく", definition: "to move" },
  "緊張する": { reading: "きんちょうする", definition: "to be nervous" },
  "贈る": { reading: "おくる", definition: "to give (a gift)" },
  "撮る": { reading: "とる", definition: "to take (a photo)" },
  "光る": { reading: "ひかる", definition: "to shine; to glow" },
  "始まる": { reading: "はじまる", definition: "to begin" },
  "上げる": { reading: "あげる", definition: "to raise; to lift" },
  "答える": { reading: "こたえる", definition: "to answer; to reply" },
  "話しかける": { reading: "はなしかける", definition: "to speak to; to address" },
  "案内する": { reading: "あんないする", definition: "to guide; to show around" },
  "登る": { reading: "のぼる", definition: "to climb" },
  "差し込む": { reading: "さしこむ", definition: "to shine in; to insert" },
  "聞こえる": { reading: "きこえる", definition: "to be audible; to hear" },
  "見える": { reading: "みえる", definition: "to be visible; to seem" },
  "疲れる": { reading: "つかれる", definition: "to get tired" },
  "落ちる": { reading: "おちる", definition: "to fall; to drop" },
  "展示する": { reading: "てんじする", definition: "to exhibit; to display" },
  "返す": { reading: "かえす", definition: "to return (something)" },
  "続く": { reading: "つづく", definition: "to continue" },
  "分かる": { reading: "わかる", definition: "to understand" },
  "好きになる": { reading: "すきになる", definition: "to come to like" },
  "声をかける": { reading: "こえをかける", definition: "to call out to" },
  "一匹": { reading: "いっぴき", definition: "one (animal)" },
  "白い": { reading: "しろい", definition: "white" },
  "赤い": { reading: "あかい", definition: "red" },
  "黄色い": { reading: "きいいろい", definition: "yellow" },
  "温かい": { reading: "あたたかい", definition: "warm" },
  "にぎやか": { reading: "にぎやか", definition: "lively; bustling" },
  "平ら": { reading: "たいら", definition: "flat; level" },
  "やさしい": { reading: "やさしい", definition: "gentle; kind" },
  "心配そう": { reading: "しんぱいそう", definition: "looking worried" },
  "嬉しそう": { reading: "うれしそう", definition: "looking happy" },
  "おいしそう": { reading: "おいしそう", definition: "looks delicious" },
  "空いている": { reading: "あいている", definition: "empty; vacant" },
  "銀色": { reading: "ぎんいろ", definition: "silver (color)" },
  "虹": { reading: "にじ", definition: "rainbow" },
  "匂い": { reading: "におい", definition: "smell; aroma" },
  "音": { reading: "おと", definition: "sound" },
  "景色": { reading: "けしき", definition: "scenery; view" },
  "席": { reading: "せき", definition: "seat" },
  "ホーム": { reading: "ホーム", definition: "platform (train)" },
  "首輪": { reading: "くびわ", definition: "collar (pet)" },
  "飼い主": { reading: "かいぬし", definition: "pet owner" },
  "しっぽ": { reading: "しっぽ", definition: "tail" },
  "ベンチ": { reading: "ベンチ", definition: "bench" },
  "女性": { reading: "じょせい", definition: "woman" },
  "飛び跳ねる": { reading: "とびはねる", definition: "to jump up" },
  "誕生日": { reading: "たんじょうび", definition: "birthday" },
  "絵": { reading: "え", definition: "picture; drawing" },
  "ペン": { reading: "ペン", definition: "pen" },
  "写真": { reading: "しゃしん", definition: "photograph" },
  "屋台": { reading: "やたい", definition: "food stall" },
  "焼きそば": { reading: "やきそば", definition: "yakisoba" },
  "綿あめ": { reading: "わたあめ", definition: "cotton candy" },
  "金魚": { reading: "きんぎょ", definition: "goldfish" },
  "肩": { reading: "かた", definition: "shoulder" },
  "来年": { reading: "らいねん", definition: "next year" },
  "漫画": { reading: "まんが", definition: "manga; comic" },
  "図書室": { reading: "としょしつ", definition: "library room" },
  "翌日": { reading: "よくじつ", definition: "next day" },
  "一週間": { reading: "いっしゅうかん", definition: "one week" },
  "笑顔": { reading: "えがお", definition: "smiling face" },
  "週末": { reading: "しゅうまつ", definition: "weekend" },
  "入口": { reading: "いりぐち", definition: "entrance" },
  "だんだん": { reading: "だんだん", definition: "gradually" },
  "急": { reading: "きゅう", definition: "steep; sudden" },
  "木々": { reading: "きぎ", definition: "trees" },
  "光": { reading: "ひかり", definition: "light" },
  "頂上": { reading: "ちょうじょう", definition: "summit; top" },
  "努力": { reading: "どりょく", definition: "effort" },
  "甲斐": { reading: "かい", definition: "worth; reward" },
  "下り道": { reading: "くだりみち", definition: "downhill path" },
  "棚": { reading: "たな", definition: "shelf" },
  "後ろ": { reading: "うしろ", definition: "behind; back" },
  "メモ": { reading: "メモ", definition: "memo; note" },
  "好奇心": { reading: "こうきしん", definition: "curiosity" },
  "卒業生": { reading: "そつぎょうせい", definition: "graduate" },
  "記録": { reading: "きろく", definition: "record; log" },
  "利用": { reading: "りよう", definition: "use; utilization" },
  "魚屋": { reading: "さかなや", definition: "fish shop" },
  "通り": { reading: "とおり", definition: "street; passage" },
  "フライパン": { reading: "フライパン", definition: "frying pan" },
  "帰り道": { reading: "かえりみち", definition: "way home" },
  "午後": { reading: "ごご", definition: "afternoon" },
  "同時": { reading: "どうじ", definition: "at the same time" },
  "おばあちゃん": { reading: "おばあちゃん", definition: "grandmother" },
  "何度": { reading: "なんど", definition: "how many times" },
  "四月": { reading: "しがつ", definition: "April" },
  "最初": { reading: "さいしょ", definition: "first; beginning" },
  "休み時間": { reading: "やすみじかん", definition: "break time" },
  "放課後": { reading: "ほうかご", definition: "after school" },
  "他": { reading: "ほか", definition: "other" },
  "中心": { reading: "ちゅうしん", definition: "center" },
  "人々": { reading: "ひとびと", definition: "people" },
  "八時": { reading: "はちじ", definition: "eight o'clock" },
  "最後": { reading: "さいご", definition: "last; end" },
  "三時": { reading: "さんじ", definition: "three o'clock" },
  "文字": { reading: "もじ", definition: "character; text" },
  "一緒に": { reading: "いっしょに", definition: "together" },
  "少しずつ": { reading: "すこしずつ", definition: "little by little" },
}

export function lookupGloss(word: string): GlossEntry | undefined {
  return GLOSSARY[word]
}
